# Generated by Django 5.0 on 2023-12-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelsPegawai',
            fields=[
                ('id_pegawai', models.AutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255, null=True)),
                ('NIP', models.CharField(max_length=255, null=True)),
                ('IP', models.CharField(max_length=255, null=True)),
                ('JABATAN', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'pegawai',
            },
        ),
    ]
